language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh r_binary_install knitr
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

env:
  global:
    - WARNINGS_ARE_ERRORS=1
    - R_BUILD_ARGS=--no-manual
    - R_CHECK_ARGS=--no-manual --as-cran
  matrix:
    - RVERSION=3.0.0
    - RVERSION=3.0.1
    - RVERSION=3.0.2
    - RVERSION=3.0.3
    - RVERSION=3.1.0
    - RVERSION=3.1.1
    - RVERSION=3.1.2
    - RVERSION=devel

notifications:
  email:
    on_success: change
    on_failure: change
